import './globals.css'

export const metadata = {
  title: 'ID Read',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-white'>
      <body className="bg-[#3A81F7] max-w-3xl h-screen flex flex-col items-center pt-8">{children}</body>
    </html>
  )
}
